### ISSUE TITLE
migrate from SAPLINK to abapGit 

### ISSUE THREAD

**Issue by hendrik77** [epeterson320/ABAP-Logger#10]
SAPLINK is kind of outdated and abapGit is a great tool. Easy to install and use. Would be great if you would migrate to abapGit for easy installation purpose of the software. 

Cheers
Hendrik

ps: https://github.com/larshp/abapGit

**Comment by epeterson320** [comment]
I would gladly accept a PR for this.

**Comment by andikade** [comment]
I am working on this. I have already checked in the classes with ZABAPGIT in a forked repository: https://github.com/andikade/ABAP-Logger/tree/move-to-abapgit

I still have to adapt the README.ME - and I had to adapt the code in order to activate it on a blank ABAP NetWeaver 7.5 System. There was some code which required business data definitions like for example BSEG which are not available on a Development System. I suggest to keep the code compatible with a Development System. What do you think?

**Comment by andikade** [comment]
I have finished my work. Please see the pull request. Feedback will be appreciated.
